name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # This replaces set-up-python and manual path manipulation
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.10'
        environment-file: environment.yml
        activate-environment: base # Change this if your environment.yml specifies a different name

    - name: Lint with flake8
      shell: bash -l {0} # This forces the step to use an activated conda environment
      run: |
        conda install -y flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0} # Ensures pytest runs inside the activated conda environment
      run: |
        conda install -y pytest
        pytest
